doc_manager/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from . import views

app_name = 'doc_manager'
urlpatterns = [
    path('', TemplateView.as_view(template_name="base_generic.html")),

    path('specifications/', views.SpecificationsView.as_view(), name='specification'),
    path('specifications/new/', views.create_specification, name='new_specification'),
    path('specifications/<int:pk>/', views.edit_specification, name='edit_specification'),
    path('specifications/<int:pk>/delete/', views.delete_specification,
          name='delete_specification'),

    path('specifications/deleted/', views.DeletedSpecificationsView.as_view(), name='deleted_specification'),
    path('specifications/deleted/<int:pk>/', views.restore_specification, name='restore_specification'),
    path('specifications/deleted/<int:pk>/delete/', views.hard_delete_specification,
          name='hard_delete_specification'),

    path('orders/', views.OrderList.as_view(), name='order'),
    path('orders/new/', views.create_order, name='new_order'),
    path('orders/<int:pk>/', views.edit_order, name='edit_order'),
    path('orders/<int:pk>/delete/', views.delete_order, name='delete_order'),
    path('orders/report/', views.OrderReportList.as_view(), name='order_report'),
    path('orders/report/download/', views.download_order_report, name='order_report_download'),

    path('execution/', views.ExecutionList.as_view(), name='execution'),
    path('execution/new/', views.create_execution, name='new_execution'),
    path('execution/<int:pk>/', views.edit_execution, name='edit_execution'),
    path('execution/<int:pk>/delete/', views.delete_execution, name='delete_execution'),

    path('orders/deleted/', views.DeletedOrderList.as_view(), name='deleted_order'),
    path('orders/deleted/<int:pk>/', views.restore_order, name='restore_order'),
    path('orders/deleted/<int:pk>/delete/', views.hard_delete_order, name='hard_delete_order'),

    path('addresses/', views.AddressList.as_view(), name='address'),
    path('addresses/new/', views.create_address, name='new_address'),
    path('addresses/<int:pk>/', views.edit_address, name='edit_address'),
    path('addresses/<int:pk>/delete/', views.delete_address, name='delete_address'),

    path('materials/', views.MaterialsList.as_view(), name='material'),
    path('materials/new/', views.create_material, name='new_material'),
    path('materials/<int:pk>/', views.edit_material, name='edit_material'),
    path('materials/<int:pk>/delete/', views.delete_material, name='delete_material'),

    path('customers/', views.CustomersList.as_view(), name='customer'),
    path('customers/new/', views.create_customer, name='new_customer'),
    path('customers/<int:pk>/', views.edit_customer, name='edit_customer'),
    path('customers/<int:pk>/delete/', views.delete_customer, name='delete_customer'),

    path('vehicles/', views.VehiclesList.as_view(), name='vehicle'),
    path('vehicles/new/', views.create_vehicle, name='new_vehicle'),
    path('vehicles/<int:pk>/', views.edit_vehicle, name='edit_vehicle'),
    path('vehicles/<int:pk>/delete/', views.delete_vehicle, name='delete_vehicle'),

    path('drivers/', views.DriversList.as_view(), name='driver'),
    path('drivers/new/', views.create_driver, name='new_driver'),
    path('drivers/<int:pk>/', views.edit_driver, name='edit_driver'),
    path('drivers/<int:pk>/delete/', views.delete_driver, name='delete_driver'),
    path('drivers/report/', views.DriverReportList.as_view(), name='driver_report'),
    path('drivers/report/download/', views.download_driver_report, name='driver_report_download'),

    path('contractor/', views.ContractorsList.as_view(), name='contractor'),
    path('contractor/new/', views.create_contractor, name='new_contractor'),
    path('contractor/<int:pk>/', views.edit_contractor, name='edit_contractor'),
    path('contractor/<int:pk>/delete/', views.delete_contractor, name='delete_contractor'),
    path('contractor/report/', views.ContractorReportList.as_view(), name='contractor_report'),
    path('contractor/report/download/', views.download_contractor_report, name='contractor_report_download'),

    path('contractor/execution/', 
         views.ContractorExecutionList.as_view(),
         name='contractor_execution'),
    path('contractor/execution/new/',
         views.create_contractor_execution,
         name='new_contractor_execution'),
    path('contractor/execution/<int:pk>/',
         views.edit_contractor_execution,
         name='edit_contractor_execution'),
    path('contractor/execution/<int:pk>/delete/',
         views.delete_contractor_execution,
         name='delete_contractor_execution'),

    path('paths/', views.PathCostList.as_view(), name='pathcost'),
    path('paths/new/', views.create_path, name='new_pathcost'),
    path('paths/<int:pk>/', views.edit_path, name='edit_pathcost'),
    path('paths/<int:pk>/delete/', views.delete_path, name='delete_pathcost'),
]

webdocs/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('docs/', include('doc_manager.urls')),
    path('', RedirectView.as_view(url='docs/'), name='main_index'),

    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
        # No profile system
    path('accounts/profile/', RedirectView.as_view(pattern_name='main_index'), name='profile'),

]

doc_manager/views.py
import datetime

from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins     import PermissionRequiredMixin

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib   import messages
from django.views     import generic
from django.urls      import reverse
from django.http.response import HttpResponse

from django.db.models import Sum, F, Q

from safedelete.models import HARD_DELETE

from . import models as the_models
from . import forms  as the_forms
from .utils import (create_generic, edit_generic, delete_generic,
                    get_report_workbook)

class SpecificationsView(generic.ListView):
    model = the_models.Specification

    def get_queryset(self):
        from_addr = self.request.GET.get('from-addr', '')
        to_addr   = self.request.GET.get('to-addr', '')
        material  = self.request.GET.get('material', '')

        queryset = self.model.objects.all()
        queryset = queryset.filter(from_addr__name__icontains=from_addr)
        queryset = queryset.filter(to_addr__name__icontains=to_addr)
        queryset = queryset.filter(material__name__icontains=material)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_path_name'] = 'doc_manager:new_specification'
        context['edit_path_name'] = 'doc_manager:edit_specification'

        context['from_addr'] = self.request.GET.get('from-addr', '')
        context['to_addr']   = self.request.GET.get('to-addr', '')
        context['material']  = self.request.GET.get('material', '')

        return context

def create_specification(request):
    return create_generic(
        request,
        form_class=the_forms.SpecificationForm,
        create_path_name='doc_manager:new_specification',
        edit_path_name='doc_manager:edit_specification',
        template_name='doc_manager/create_edit_generic.html'
    )

def edit_specification(request, pk):
    spec = the_models.Specification.objects.get(pk=pk)
    related_objs = spec.order_set.all()

    return edit_generic(
        request, pk,
        form_class=the_forms.SpecificationForm,
        model_class=the_models.Specification,
        edit_path_name='doc_manager:edit_specification',
        delete_path_name='doc_manager:delete_specification',
        template_name='doc_manager/create_edit_generic.html',
        context_args={
            'related_objects_list': related_objs,
        }
    )

def delete_specification(request, pk):
    return delete_generic(
        request, pk,
        model_class=the_models.Specification,
        list_url_name='doc_manager:specification'
    )

class DeletedSpecificationsView(PermissionRequiredMixin, generic.ListView):
    model = the_models.Specification
    permission_required = [
        'doc_manager.undelete_specification',
        'doc_manager.hard_delete_specification',
    ]

    def get_queryset(self):
        from_addr = self.request.GET.get('from-addr', '')
        to_addr   = self.request.GET.get('to-addr', '')
        material  = self.request.GET.get('material', '')

        queryset = self.model.objects.deleted_only()
        queryset = queryset.filter(from_addr__name__icontains=from_addr)
        queryset = queryset.filter(to_addr__name__icontains=to_addr)
        queryset = queryset.filter(material__name__icontains=material)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['edit_path_name'] = 'doc_manager:restore_specification'

        context['from_addr'] = self.request.GET.get('from-addr', '')
        context['to_addr']   = self.request.GET.get('to-addr', '')
        context['material']  = self.request.GET.get('material', '')

        return context

@permission_required('doc_manager.undelete_specification')
def restore_specification(request, pk):
    spec = the_models.Specification.objects.deleted_only().get(pk=pk)

    if request.method == "POST":
        form = the_forms.SpecificationForm(request.POST, instance=spec)
        if form.is_valid():
            form.save()

            message = f'Восстановлено: {form.instance}'
            messages.success(request, message)

            return redirect('doc_manager:edit_specification', pk=form.instance.pk)
    else:
        form = the_forms.SpecificationForm(instance=spec)

    action = reverse('doc_manager:restore_specification',
                     kwargs={'pk':spec.pk})
    
    delete_action = reverse('doc_manager:hard_delete_specification',
                     kwargs={'pk':spec.pk})
    
    context = {
        'delete_action': delete_action,
        'action':        action,
        'form':          form,
    }

    return render(request, 'doc_manager/create_edit_generic.html', context=context)

@permission_required('doc_manager.hard_delete_specification')
def hard_delete_specification(request, pk):
    spec = the_models.Specification.objects.deleted_only().get(pk=pk)
    spec_str = str(spec)
    spec.delete(force_policy=HARD_DELETE)

    message = f'Удалено: {spec_str}'
    messages.success(request, message)

    return redirect('doc_manager:deleted_specification')

class OrderList(generic.ListView):
    model = the_models.Order

    def get_queryset(self):
        start_date_value = self.request.GET.get('start_date')
        end_date_value   = self.request.GET.get('end_date')
        get_unfinished_orders = self.request.GET.get('unfinished_orders')

        queryset = self.model.objects.all()
        if start_date_value:
            queryset = queryset.filter(date__gte=start_date_value)
        if end_date_value:
            queryset = queryset.filter(date__lte=end_date_value)
        if get_unfinished_orders:
            queryset = queryset.filter(
                Q(driver__isnull=True) & Q(contractor__isnull=True) 
                | Q(path__isnull=True)
            )

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_path_name'] = 'doc_manager:new_order'
        context['edit_path_name'] = 'doc_manager:edit_order'

        context['start_date_value']  = self.request.GET.get('start_date', '')
        context['end_date_value']    = self.request.GET.get('end_date', '')
        context['unfinished_orders'] = self.request.GET.get('unfinished_orders', '')

        return context

def create_order(request):
    return create_generic(
        request,
        form_class=the_forms.OrderForm,
        create_path_name='doc_manager:new_order',
        edit_path_name='doc_manager:edit_order',
        template_name='doc_manager/order.html',
        context_args={
            'specification_list': the_models.Specification.objects.all(),
        }
    )

def edit_order(request, pk):
    return edit_generic(
        request, pk,
        form_class=the_forms.OrderForm,
        model_class=the_models.Order,
        edit_path_name='doc_manager:edit_order',
        delete_path_name='doc_manager:delete_order',
        template_name='doc_manager/order.html',
        context_args={
            'specification_list': the_models.Specification.objects.all(),
        }
    )

def delete_order(request, pk):
    order = the_models.Order.objects.get(pk=pk)

    if order.exec_doc is not None:
        message = f'Невозможно удалить, так как заказ связан с УПД'
        messages.error(request, message)
        return redirect('doc_manager:edit_order', pk=order.pk)

    if order.contr_doc is not None:
        message = f'Невозможно удалить, так как заказ связан с УПД подрядчика'
        messages.error(request, message)
        return redirect('doc_manager:edit_order', pk=order.pk)

    order_str = str(order)
    order.delete()
    message = f'Удалено: {order_str}'
    messages.success(request, message)

    return redirect('doc_manager:order')

class OrderReportList(generic.ListView):
    model = the_models.Order
    template_name="doc_manager/order_report.html"

    def get_queryset(self):
        customer_id      = self.request.GET.get('customer')
        start_date_value = self.request.GET.get('start_date')
        end_date_value   = self.request.GET.get('end_date')

        queryset = self.model.objects.all()
        if customer_id:
            queryset = queryset.filter(specification__customer=customer_id)
        if start_date_value:
            queryset = queryset.filter(date__gte=start_date_value)
        if end_date_value:
            queryset = queryset.filter(date__lte=end_date_value)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['customer_list']    = the_models.Customer.objects.all()
        context['customer_value']   = self.request.GET.get('customer', '')
        context['start_date_value'] = self.request.GET.get('start_date', '')
        context['end_date_value']   = self.request.GET.get('end_date', '')

        totals = self.get_queryset().aggregate(
            metres_total=Sum('count', filter=Q(specification__units='m3')),
            tonnes_total=Sum('count', filter=Q(specification__units='t')),
            metres_sum=Sum(F('specification__price') * F('count'), filter=Q(specification__units='m3')),
            tonnes_sum=Sum(F('specification__price') * F('count'), filter=Q(specification__units='t')),
        )
        for key, value in totals.items():
            context[key] = 0 if value is None else value

        context['total_sum'] = context['metres_sum'] + context['tonnes_sum']

        return context

def download_order_report(request):
    model = the_models.Order
    customer_id      = request.GET.get('customer')
    start_date_value = request.GET.get('start_date')
    end_date_value   = request.GET.get('end_date')

    queryset = model.objects.all()
    if customer_id:
        queryset = queryset.filter(specification__customer=customer_id)

doc_manager/templates/doc_manager/address_list.html
{% extends "doc_manager/table_generic.html" %}

{% block title %}Список адресов - {{ block.super }}{% endblock%}

{% block page_head %}Список адресов{% endblock %}

{% block table_input %}
<form method="GET">
    <input 
        type="text" 
        name="name" 
        id="name-filter" 
        placeholder="Полный адрес"
        value="{{name_value}}">
    <button type="submit">Найти</button>
</form>
{% endblock %}

{% block table_header %}
    <th scope="col">#</th>
    <th scope="col">Полный адрес</th>
{% endblock %}

{% block table_row %}
    <th scope="row">{{object.pk}}</th>
    <td>{{object.name}}</td>
{% endblock %}

{% block no_objects_found %}
    <p>Адресов не найдено</p>
{% endblock %}

doc_manager/templates/doc_manager/contractor_execution_list.html
{% extends "doc_manager/table_generic.html" %}

{% block title %}УПД подрядчиков - {{ block.super }}{% endblock%}

{% block page_head %}УПД подрядчиков{% endblock %}

{% block table_input %}
<form method="GET">
    <select name="contractor">
        <option value="">---------</option>
        {% for contractor in contractor_list %}
        <option value="{{contractor.pk}}"
                {% if contractor.pk == contractor_value|add:"0" %}selected{% endif %}>
            {{contractor}}
        </option>
        {% endfor %}
    </select>
    <label for="id_start_date">Начало: </label>
    <input type="date" id="id_start_date" name="start_date" value="{{start_date_value}}">
    <label for="id_end_date">Конец: </label>
    <input type="date" id="id_end_date" name="end_date" value="{{end_date_value}}">
    <button type="submit">Найти</button>
</form>
{% endblock %}

{% block table_header %}
    <th scope="col">#</th>
    <th scope="col">Дата</th>
    <th scope="col">Подрядчик</th>
    <th scope="col">Сумма</th>
{% endblock %}

{% block table_row %}
    <th scope="row">{{object.exec_no}}</th>
    <td>{{object.date|date:"d.m.Y"}}</td>
    <td>{{object.contractor}}</td>
    <td>{{object.sum}}</td>
{% endblock %}

{% block no_objects_found %}
    <p>УПД подрядчиков не найдено</p>
{% endblock %}

doc_manager/templates/doc_manager/contractor_report.html
{% extends "doc_manager/table_generic.html" %}

{% block title %}Отчет по подрядчикам - {{ block.super }}{% endblock%}

{% block page_head %}Отчет по подрядчикам{% endblock %}

{% block table_input %}
<form method="GET">
    <select name="contractor">
        <option value="">---------</option>
        {% for contractor in contractor_list %}
        <option value="{{contractor.pk}}"
                {% if contractor.pk == contractor_value|add:"0" %}selected{% endif %}>
            {{contractor}}
        </option>
        {% endfor %}
    </select>
    <label for="id_start_date">Начало: </label>
    <input type="date" id="id_start_date" name="start_date" value="{{start_date_value}}">
    <label for="id_end_date">Конец: </label>
    <input type="date" id="id_end_date" name="end_date" value="{{end_date_value}}">
    <button type="submit">Найти</button>
</form>
{% endblock %}

{% block table_header %}
    <th scope="col">#</th>
    <th scope="col">Подрядчик</th>
    <th scope="col">Дата</th>
    <th scope="col">Фактич.<br>погрузка</th>
    <th scope="col">Фактич.<br>выгрузка</th>
    <th scope="col">Ставка</th>
    <th scope="col">УПД</th>
    <th scope="col">Номер<br>УПД</th>
    <th scope="col">Дата<br>УПД</th>
{% endblock %}

{% block table_row %}
    <th scope="row">{{object.id}}</th>
    <td>{{object.contractor}}</td>
    <td>{{object.date|date:"d.m.Y"}}</td>
    <td>{{object.path.path_from}}</td>
    <td>{{object.path.path_to}}</td>
    <td>{{object.path.cost}}</td>
    <td>{{object.contr_doc|yesno:"Да,Нет"}}</td>
    <td>{{object.contr_doc.exec_no|default:""}}</td>
    <td>{{object.contr_doc.date|date:"d.m.Y"|default:""}}</td>
{% endblock %}

{% block table_footer %}
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <th scope="row">Итог:</th>
    <td>{{ total }}</td>
{% endblock %}

{% block post_table %}

<a href="{% url 'doc_manager:contractor_report_download' %}?start_date={{start_date_value}}&end_date={{end_date_value}}&contractor={{contractor_value}}"
   class="btn btn-primary">
    Выгрузить в Excel
</a>

{% endblock %}

{% block no_objects_found %}
    <p>Поездок не найдено</p>
{% endblock %}

doc_manager/templates/doc_manager/create_edit_generic.html
{% extends "base_generic.html" %}

{% load crispy_forms_tags %}
{% load extras %}
{% load static %}

{% block title %}{% get_verbose_name form.instance %} - {{ block.super }}{% endblock%}

{% block content %}

<div class="p-3 text-center">
    <h1>
        {% block page_head %}
        {% if form.instance.pk %}
            {% if form.instance.deleted %}
                Восстановить:
            {% else%}
                Изменить:
            {% endif %}
        {% else %}
            Создать:
        {% endif %}
        {% get_verbose_name form.instance %}
        {% endblock %}
    </h1>
</div>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li class="alert {% if message.tags %}{{ message.tags }}{% else %}alert-primary{% endif %}"
      role="alert">
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

<form action="{{ action }}" method="post">

    {% crispy form %}

    {% if form.instance.deleted %}
        <p>Объект помечен на удаление: {{form.instance.deleted|date:"d.m.Y, G:i"}}</p>
    {% endif %}

    {% if form.instance.pk %}
    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete-modal">
        Удалить
    </button>
    {% endif %}

    <button type="submit" class="btn btn-primary">
        {% if form.instance.pk %}
            {% if form.instance.deleted %}
                Восстановить
            {% else%}
                Изменить
            {% endif %}
        {% else%}
            Добавить
        {% endif %}
    </button>
</form>

{% if form.instance.pk %}
<form action="{{ delete_action }}" method="post">
    {% csrf_token %}

    <div class="modal fade" id="delete-modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Удаление объекта</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                {% if related_objects_list %}
                    Невозможно удалить объект, так как от него зависят следющие объекты:
                    <ul>
                    {% for object in related_objects_list %}
                        <li>{{object.pk}}: {{object}}</li>
                    {% endfor %}
                    </ul>
                {% else %}
                    Удалить объект?
                {% endif %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                    {% if not related_objects_list %}
                    <button type="submit" class="btn btn-primary">Удалить</button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

</form>
{% endif %}

{% endblock %}

{% block body_scripts %}
    <script src="{% static 'doc_manager/js/select_search.js' %}"></script>
{% endblock %}

doc_manager/templates/doc_manager/driver_list.html
{% extends "doc_manager/table_generic.html" %}

{% block title %}Список водителей - {{ block.super }}{% endblock%}

{% block page_head %}Список водителей{% endblock %}

{% block table_input %}
<form method="GET">
    <input 
        type="text" 
        name="name" 
        id="name-filter" 
        placeholder="ФИО"
        value="{{name_value}}">
    <button type="submit">Найти</button>
</form>
{% endblock %}

{% block table_header %}
    <th scope="col">#</th>
    <th scope="col">ФИО</th>
{% endblock %}

{% block table_row %}
    <th scope="row">{{object.pk}}</th>
    <td>{{object.name}}</td>
{% endblock %}

{% block no_objects_found %}
    <p>Водителей не найдено</p>
{% endblock %}

doc_manager/templates/doc_manager/driver_report.html
{% extends "doc_manager/table_generic.html" %}

{% block title %}Отчет по водителям - {{ block.super }}{% endblock%}

{% block page_head %}Отчет по водителям{% endblock %}

{% block table_input %}
<form method="GET">
    <select name="driver">
        <option value="">---------</option>
        {% for driver in driver_list %}
        <option value="{{driver.pk}}"
                {% if driver.pk == driver_value|add:"0" %}selected{% endif %}>
            {{driver}}
        </option>
        {% endfor %}
    </select>
    <label for="id_start_date">Начало: </label>
    <input type="date" id="id_start_date" name="start_date" value="{{start_date_value}}">
    <label for="id_end_date">Конец: </label>
    <input type="date" id="id_end_date" name="end_date" value="{{end_date_value}}">
    <button type="submit">Найти</button>
</form>
{% endblock %}

{% block table_header %}
    <th scope="col">#</th>
    <th scope="col">Водитель</th>
    <th scope="col">Дата</th>
    <th scope="col">Фактич.<br>погрузка</th>
    <th scope="col">Фактич.<br>выгрузка</th>
    <th scope="col">Ставка</th>
{% endblock %}

{% block table_row %}
    <th scope="row">{{object.id}}</th>
    <td>{{object.driver}}</td>
    <td>{{object.date|date:"d.m.Y"}}</td>
    <td>{{object.path.path_from}}</td>
    <td>{{object.path.path_to}}</td>
    <td>{{object.path.cost}}</td>
{% endblock %}

{% block table_footer %}
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <th scope="row">Итог:</th>
    <td>{{ total }}</td>
{% endblock %}

{% block post_table %}

<a href="{% url 'doc_manager:driver_report_download' %}?start_date={{start_date_value}}&end_date={{end_date_value}}&driver={{driver_value}}"
   class="btn btn-primary">
    Выгрузить в Excel
</a>

{% endblock %}

{% block no_objects_found %}
    <p>Поездок не найдено</p>
{% endblock %}

doc_manager/templates/doc_manager/order_report.html
{% extends "doc_manager/table_generic.html" %}

{% block title %}Отчет по заказам - {{ block.super }}{% endblock%}

{% block page_head %}Отчет по заказам{% endblock %}

{% block table_input %}
<form method="GET">
    <select name="customer">
        <option value="">---------</option>
        {% for customer in customer_list %}
        <option value="{{customer.pk}}"
                {% if customer.pk == customer_value|add:"0" %}selected{% endif %}>
            {{customer}}
        </option>
        {% endfor %}
    </select>
    <label for="id_start_date">Начало: </label>
    <input type="date" id="id_start_date" name="start_date" value="{{start_date_value}}">
    <label for="id_end_date">Конец: </label>
    <input type="date" id="id_end_date" name="end_date" value="{{end_date_value}}">
    <button type="submit">Найти</button>
</form>
{% endblock %}

{% block table_header %}
    <th scope="col">#</th>
    <th scope="col">Дата<br>создания</th>
    <th scope="col">Номер<br>спец.</th>
    <th scope="col">Заказчик</th>
    <th scope="col">Фактич.<br>погрузка</th>
    <th scope="col">Фактич.<br>выгрузка</th>
    <th scope="col">Цена<br>за ед.</th>
    <th scope="col">Ед.<br>изм.</th>
    <th scope="col">Кол-во</th>
    <th scope="col">Сумма</th>
    <th scope="col">УПД</th>
    <th scope="col">Номер<br>УПД</th>
    <th scope="col">Дата<br>УПД</th>
{% endblock %}

{% block table_row %}
    <th scope="row">{{object.id}}</th>
    <td>{{object.date|date:"d.m.Y"}}</td>
    <td>{{object.specification.doc_no}}</td>
    <td>{{object.specification.customer}}</td>
    <td>{{object.path.path_from|default:""}}</td>
    <td>{{object.path.path_to|default:""}}</td>
    <td>{{object.specification.price}}</td>
    <td>{{object.specification.get_units_display}}</td>
    <td>{{object.count}}</td>
    <td>{{object.price}}</td>
    <td>{{object.exec_doc|yesno:"Да,Нет"}}</td>
    <td>{{object.exec_doc.exec_no|default:""}}</td>
    <td>{{object.exec_doc.date|date:"d.m.Y"|default:""}}</td>
{% endblock %}

{% block post_table %}
<div class="col-4">
<table class="table">
    <thead>
        <tr>
            <th scope="col">Ед. изм.</th>
            <th scope="col">Кол-во</th>
            <th scope="col">Сумма</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Куб. метры</td>
            <td>{{metres_total | default:"0"}}</td>
            <td>{{metres_sum | default:"0"}}</td>
        </tr>
        <tr>
            <td>Тонны</td>
            <td>{{tonnes_total | default:"0"}}</td>
            <td>{{tonnes_sum | default:"0"}}</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td></td>
            <td>Итого: </td>
            <td>{{total_sum | default:"0"}}</td>
        </tr>
    </tfoot>
</table>

<a href="{% url 'doc_manager:order_report_download' %}?start_date={{start_date_value}}&end_date={{end_date_value}}&customer={{customer_value}}"
   class="btn btn-primary">
    Выгрузить в Excel
</a>

</div>
{% endblock %}

{% block no_objects_found %}
    <p>Заказов не найдено</p>
{% endblock %}